name: Update Workflow

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub"
          git config user.email "gitactio@outlook.com"

      - name: Apply changes
        run: |
          echo "Update" > workflow.txt
          git add .
          git commit -m "Routine update"
          git push
